### ISSUE TITLE
Are the "Build & install Boost 1.50 in CentOS" instructions still valid?

### ISSUE THREAD

**Issue by travispaul** [jackywei/HOW-TO-BUILD-HHVM-WiKi#2]
I followed the hiphop wiki's [CentOS build instructions](https://github.com/facebook/hiphop-php/wiki/Building-and-installing-HHVM-on-CentOS-6.3)  and the [GCC 4.6.3 build instructions](https://github.com/jackywei/HOW-TO-BUILD-HHVM-WiKi/wiki/Build-%26-Install-GCC4.6.3-in-CentOS-%285.2-%26-6.3%29)

And I also needed to build a newer version of CMake, which wasn't in the wiki.

I then tried to build hiphop and got an error that my boost version was too old so I followed the [boost build instructions](https://github.com/jackywei/HOW-TO-BUILD-HHVM-WiKi/wiki/Build-%26-install-Boost-1.50-in-CentOS-%28CentOS5.2-%26-6.3-are-both-verified%29)

I built boost and no longer receive the erro about my boost version but when I build hiphop I get the error:

`hiphop-php/hphp/third_party/folly/folly/detail/ThreadLocalDetail.h:204:7: error: ‘lock_guard’ is not a member of ‘boost’`

Are those instructions still valid?

**Comment by jackywei** [comment]
I think the boost instruction is still valid. But I did not build the latest version of hhvm, will try to rebuild and give you some feedback. stay tuned.

**Comment by jackywei** [comment]
I just tried, it is ok for my side.

My environment is CentOS6.3 which already been installed old hhvm before(the version should be around March), I remove the whole old hiphop-php folder. And unzip the latest code(today's), and upgraded CMake according to https://github.com/jackywei/HOW-TO-BUILD-HHVM-WiKi/wiki/Build-&-Install-CMake-2.8.10.2-in-CentOS6.3. redo the cmake. and make. it is ok now. 

But during my building process, I met different error message from you, these error show some .sh(only 2, one is hiphop-php/hphp/util/generate_buildinfo.sh, another is hiphop-php/hphp/tools/gen-ext-hhvm/gen-ext-hhvm.sh) files are not excutable. I just used the "chmod 777 *.sh" to change these file to excutable. then will be ok for building.

**Comment by jackywei** [comment]
I checked my boost version, still is 1.50 which was built before. I did not change this.

**Comment by travispaul** [comment]
Thanks, I must have missed a step somewhere I'll rebuild boost today and see if I get better results.

**Comment by travispaul** [comment]
I think I had some remnants of the stock CentOS boost library. I uninstalled them (with yum), manually removed all boost libs that were installed, rebuilt boost and was then able to compile. However A few hours ago someone added a [CentOS 6.4 repo](https://github.com/facebook/hiphop-php/wiki/HHVM-Pre-built-packages-for-Centos-6.4) to the HHVM wiki which is what I will probably use moving forward.

Your instructions were very helpful, thanks
